### ISSUE TITLE
Total Amount Remaining in the manageExpenditures component displays with the USD currency label even when the currency is not USD

### ISSUE THREAD

**Issue by jamesbsfdc** [SalesforceFoundation/OutboundFundsNPSP#18]
### Summary of the Issue

Where the default org currency of the org is not USD, or where the org is a multi-currency org and a Disbursement record is not in USD, the Total Amount Remaining will display with the USD currency label instead of the default currency in the org or the currency of the disbursement record.

**Screenshot**

![Manage Expenditures](https://user-images.githubusercontent.com/59653509/92243986-3a707e00-eeba-11ea-9422-b653584521cf.png)

There is a hard-coded reference to USD in the template for the Manage Expenditures:
https://github.com/SalesforceFoundation/OutboundFundsNPSP/blob/a8a630c677d5e37c1eca20287f72812a717cb888/force-app/main/default/lwc/manageExpenditures/manageExpenditures.html (line 59)

### Steps to Reproduce

**In a single currency org**

1. Ensure the default currency is any currency but USD
2. Create a Funding Program
3. Create a Funding Request for the Funding Program Request record with an Awarded Amount > 0
4. Create a Disbursement for the Funding Request with an Amount >0
5. Click on the GAU Expenditures tab within the Disbursement

Expected Result
Total Amount Remaining should display in the org currency, or the currency of the Funding Request / Disbursement

Actual Result
Total Amount Remaining displays with the USD currency label.

**In a multi-currency org**

1. Create a Funding Program
2. Create a Funding Request for the Funding Program Request record with an Awarded Amount > 0 and currency not equal to USD
3. Create a Disbursement for the Funding Request with an Amount >0 and currency not equal to USD
4. Click on the GAU Expenditures tab within the Disbursement and notice the Total Amount Remain value displays with the USD label

Expected Result
Total Amount Remaining should display in the currency of the Funding Request / Disbursement

Actual Result
Total Amount Remaining displays with the USD currency label.

**Comment by jamesbsfdc** [comment]
W-8047820

**Comment by jamesbsfdc** [comment]
[Hub post](https://powerofus.force.com/s/question/0D51E00005Q1mhT/total-amount-remaining-is-displayed-as-usd-although-my-company-uses-aud-how-can-i-change-it)

**Comment by thombehrens** [comment]
Hi @jamesbsfdc I am going to take a look at this.

**Comment by jamesbsfdc** [comment]
Nice one @thombehrens ! :)

**Comment by seanpat09** [comment]
https://github.com/SalesforceFoundation/OutboundFundsNPSP/pull/20 fixes this issue in that it will get the Total Amount Remaining to display in the user's default currency, but there are other issues regarding compatibility with multi-currency orgs. I captured that in https://github.com/SalesforceFoundation/OutboundFundsNPSP/issues/21 so this issue is good to close once https://github.com/SalesforceFoundation/OutboundFundsNPSP/pull/20 is merged
